import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { Toaster } from "sonner";
import AppProvider from "@/app/AppProvider";
import { cookies } from "next/headers";

const inter = Inter({
    subsets: ["latin", "vietnamese"],
    display: "swap", // Giúp font hiển thị nhanh hơn, tránh hiện tượng trắng trang khi chờ tải font
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const sessionTokenCookie = cookieStore.get("sessionToken");

    // Chỉ lấy phần .value, nếu không có thì để chuỗi rỗng
    const sessionToken = sessionTokenCookie?.value || "";
    return (
        <html lang="vi" suppressHydrationWarning>
            <body className={`${inter.className} antialiased`}>
                <Toaster />
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    <Header />
                    <AppProvider initialSessionToken={sessionToken}>{children}</AppProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
